hour: 20 # Hour at which time will be 14:00 Eastern Time (integer)
username: username # arXiv username
password: password # arXiv password
paperlink: https://arxiv.org/submit/XXXXXXX/preview # arXiv paper link
chromedriver: /opt/homebrew/bin/chromedriver # path to Chromedriver