[workspace]
authors = ["TheSkyentist <raphael.hviding@gmail.com>"]
channels = ["conda-forge"]
name = "chromedriver"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
pyyaml = ">=6.0.2,<7"
selenium = ">=4.33.0,<5"
